version: "3.8"

services:
  web:
    build: .
    # command: gunicorn Recruitment.wsgi:application --bind 0.0.0.0:8080
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file: .env
    environment: 
      - POSTGRES_PASSWORD=postgrespas
    # build: .
    # container_name: dbps
    # ports:
    #   - 5432:5432
volumes:
  postgres:
